/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/card/index.vue')['default']
    copy: typeof import('./components/slideshow/index copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dialog: typeof import('./components/dialog/index.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlobalSearch: typeof import('./components/global-search/GlobalSearch.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Index1: typeof import('./components/slide/index1.vue')['default']
    Index2: typeof import('./components/slide/index2.vue')['default']
    Item: typeof import('./components/carousel/item/index.vue')['default']
    Main: typeof import('./components/carousel/main/index.vue')['default']
    MvCard: typeof import('./components/card/mv-card.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/slide/index.vue')['default']
    Slideshow: typeof import('./components/slideshow/index.vue')['default']
    SongCard: typeof import('./components/card/song-card.vue')['default']
    Theme: typeof import('./components/Theme.vue')['default']
  }
}
